---
title: "Notícia"
author: "Javier Ribal del Río"
date: "2020-21"
output:
  html_document:
    css: estilos.css
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: yes
    fig_width: 5
    fig_height: 4
    fig_caption: yes
    theme: united
    anchor_sections: false
  pdf_document:
    toc: yes
    toc_depth: '4'
---
<!--Necesario-->
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```

# Definició
La notícia es un text **periodístic** és un text de tipus narratiu que té com objectiu informar de fets o accions d'interés general ocorreguts recientment.

# Característiques
- Objetivitat
- Sencillesa
- Claritat
- Concistencia
- Llenguatge estàndar
- Fonts fiables<br>
Per a transmetre credibilitat
  - Informació
  - Documentació gràfica
  - Escrita
  - Sonora
  
# Parts
  
## Autoria o redacció

Nom del periosdísta o agència que elabora la notícia. Lloc de la redacció.

## Titular o títol

**Enunciat breu**, situat a l'encapçalament de manera molt destacada, designa el contingut essencial d'una notícia.

## Entradeta o *lead*
És el primer paràgraf, escrit amb una tipografia diferent, que conté les dades essencials del fet o acció. Serveix per a que el lector es puga fer-se'n una idea completa sense llegir la resta del text.

## Peu de foto

Comentari breu sobre la fotografia. Autoria de la fotografia

## Cos

Part més ampla la qual presenta l'informació del fet o acció o situació. Sol estar divit en paràgrafs, distribuïts en diferents columnes

### Informacio del cos

- Versemblant
- Coherent
- Cohesionada
- Adequada

# Característiques de la informació

Totes les noticias han de contestar a les següents prenguntes:

## Qui?

Protasgonista de la acció

## Què?

El fet

## On?

El lloc

## Quan?

El temps

## Com?

Les circumstàncies

## Per què?

La causa

<br>
<hr color="firebrick">
<br>

## Sis W

Aquest es el nom que rebren el conjunt d'aquestes preguntes, en l'argot del periodisme. 

- Who?
- What?
- Where?
- When?
- How?
- Why?

<div class="peque">
Això ve perquè totes les preguntes contenen la lletra "w" en angles.</div>



La resposta a les quatre primeres preguntes("Qui?", "Qué?", "On?" i "Quan?") han d'aparéixer en el titular o entradeta. Per contrapart les dos ultimes ("Com?" i "Per què?") poden aparéixer en el cos.

# Estructura

Es diu que l'estructura de la notícia te forma de piràmide invertida ja que presenta més informació al principi de la notícia que cap al final. Això es fa per a **Dosificar la Informació**.

<br>

<br>


<br>
<div class="Tablon_Botones">
<a href="index.html"><button class="boton">Retornar a la Página Principal</button></a>

</div>





