---
title: "Poesia"
author: "Matteo Bozzo Solar"
date: "2020-21"
output:
  html_document:
    css: estilos.css
    toc: yes
    toc_float: yes
    toc_depth: 4
    number_sections: yes
    fig_width: 5
    fig_height: 4
    fig_caption: yes
    theme: united
  pdf_document:
    toc: yes
    toc_depth: '4'
---
<!--Necesario-->
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```
# Definició
Composició literaria escrita en vers.

  

# Elements de la poesia:

## El vers:

Línies del poema.Tenen mètrica (el nombre de síl·labes).

### Segons el nombre de síl·labes:

-   Art menor, tenen un màxim de 8 síl·labes.
    
-   Art major, tenen 9 síl·labes o més.
    

### Mètrica
 Es conta de la primera a l’última síl·laba.

### Fenómens

#### Sinalefa 

Última síl·laba d’una paraula acabada en vocal i la següent comença per vocal, s'uneixen en una sola síl·laba.
    
#### Elisió 

Dos paraules pronunciades quasi iguals formen una sola síl·laba.
    
#### Hiat

Pronunciació en síl·labes diferents de dues vocals en contacte.
    

  

## La rima:

Repetició total o parcial de sons al final de dos versos o més a partir de l’última síl·laba tònica.
### Tipus de rima:

-   Assonant: només coincideixen les vocal (clara/anava)
    
-   Consonant: coincideixen vocals i consonants (guerra/terra)
    

  

## L’esquema mètric:

Notació de la mesura dels versos i de la rima.

Les lletres en ordre alfabètic serveixen per a assenyalar els versos que rimen. Amb majúscules per als versos d’art major i amb minúscules per als d’art menor.

Els versos sense rima es representen amb un guió.

  

## L’estrofa:

Conjunt de versos enllaçats per la rima o pel sentit.

### Tipus d’estrofes:

-   Apariat: 2 versos assonants o consonants.
    
-   Tercet: 3 versos d’art major.
    
-   Quarteta/Quartet: 4 versos d’art menor (quarteta), o d’art major (quartet).Pot ser de rima encadenada (ABAB) o de rima creuada (ABBA).
    
-   Quinteta/Quintet: 5 versos d’art menor (quinteta), o d’art major (quintet).
    
-   Sexteta/Sextet: 6 versos d’art menor (sexteta), o d’art major (sextet).
    
-   Octava o Cobla clàssica: 2 quartets decasíl·labs (de 10 síl·labes), amb rimes de forma encadenada o creuada.
   
## Els recursos expressius:

Llenguatge especial (recursos expressius i figures retòriques) empleades per l’autor a la poesia.

### Tipus de recursos expressius:

 - Afecte a la fonètica:
	 - Aliteració, repetició d’uns sons determinats.
	 - Anàfora, repetició d’una paraula o expressió a l’inici de cada vers.
 - Afecten a la sintaxi:
	 - Hipèrbaton, alteració de l’ordre sintàctic lógic de l’oració.
	 - Paral·lelisme, repetició de la mateixa estructura sintàctica en
	   diferents versos.
	 - Polisíndeton, repetició d’una conjunció.
	 - Encavalcament, la pausa del vers no correspon a la pausa sintàctica.
 - Afecten el significat:
	 - Comparació, relació d’analogia entre un terme real i un imaginari.
	 - Metàfora, identificació imaginada entre dos termes pròxims.
	 - Hipèrbole, exageració que deforma la realitat.
	 - Antítesi, oposició de dos conceptes que són o semblen contradictoris.
	 - Personificació, atribuació de qualitats humanes a éssers no humans.


<div class="Tablon_Botones">
<a href="index.html"><button class="boton">Retornar a la Pàgina Principal</button></a>

<br>

<a href="ejemploPoesia.html"><button class="boton">Exemple Poesia</button></a>

</div>